name: Build the library on multiple platforms to ensure compatibility 
on: [push]

jobs:
    build:
        name: Builds the software
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        steps:
          - uses: actions/checkout@v1
          - name: Fetch build dependencies
            run: |
                pip3 install setuptools conan
                conan install .
          - name: Build the file
            run: |
                cmake -DUSE_CONAN=ON .
                cmake --build .
