name: Build the library on multiple platforms to ensure compatibility 
on: [push]

jobs:
    build:
        name: Builds the software
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        steps:
          - uses: actions/checkout@v1
          - uses: actions/setup-python@v2
            with:
                python-version: 3.6
          - name: Fetch build dependencies
            run: |
                pip3 install conan
                conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
                conan install .
          - name: Build the file
            run: |
                cmake -DUSE_CONAN=ON .
                cmake --build .
