name: Ensure that code follows our Coding Styles
on: [push]

jobs:
    build:
        name: Parses files to ensure that 
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v1
          - name: Fetch dependencies
            run: |
                sudo apt-get install python3-venv
                python3 -m venv venv
                source venv/bin/activate
                pip3 install wheel
                pip3 install -r .linter/requirements.txt
          - name: Lint files
            run: |
                ./venv/bin/coala --non-interactive
